; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32cam]
; URGENTE: Usar la versión 6.6.0 que corresponde al Core 2.0.14 de Arduino
platform = espressif32 @ 6.6.0

board = esp32cam
framework = arduino

; --- GESTIÓN DE MEMORIA CRÍTICA ---
; 1. Partición gigante para que quepa el código (APP)
board_build.partitions = huge_app.csv
; 2. Modo seguro de lectura de memoria (Evita el 'flash read err')
board_build.flash_mode = dio

; --- VELOCIDAD ---
upload_speed = 921600
monitor_speed = 115200

; --- BANDERAS DE COMPILACIÓN ---
build_flags =
    ; Hardware
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    
    ; Edge Impulse (Memoria)
    -DEI_CLASSIFIER_ALLOCATION_HEAP=1
    ; Intentamos 256KB. Si se reinicia en bucle, baja esto a 131072 (128KB)
    -DEI_CLASSIFIER_TENSOR_ARENA_SIZE=262144 
    -DCONFIG_SPIRAM_USE_MALLOC

; Librerías (Descomenta cuando confirmes que la cámara funciona)
lib_deps =
    ;madhephaestus/ESP32Servo @ ^1.1.0
    ;ikalhart/TinyGPSPlus @ ^1.0.3
    ;plerup/EspSoftwareSerial @ ^8.2.0